# This file is autogenerated from update_deps.sh.
{
  binutils-esp32s2ulp-linux-amd64-2_28_51-esp-20191205 = {
    sha256 = "0rm4p60kgzcq8sy166ad2rfq638qd36xpdmlwg5sf667qzv2yyyz";
    url = "https://github.com/espressif/binutils-esp32ulp/releases/download/v2.28.51-esp-20191205/binutils-esp32s2ulp-linux-amd64-2.28.51-esp-20191205.tar.gz";
  };
  binutils-esp32ulp-linux-amd64-2_28_51-esp-20191205 = {
    sha256 = "1mq3pjjgqczqsydf5815za7gla0z3ny6k64pv5dig08iapyc85ih";
    url = "https://github.com/espressif/binutils-esp32ulp/releases/download/v2.28.51-esp-20191205/binutils-esp32ulp-linux-amd64-2.28.51-esp-20191205.tar.gz";
  };
  openocd-esp32-linux64-0_10_0-esp32-20191114 = {
    sha256 = "1rg5yrwckz0xcj9p2zra7pdpifrijcqdljwxqxi9glax6kl170lp";
    url = "https://github.com/espressif/openocd-esp32/releases/download/v0.10.0-esp32-20191114/openocd-esp32-linux64-0.10.0-esp32-20191114.tar.gz";
  };
  xtensa-esp32-elf-gcc8_2_0-esp-2020r2-linux-amd64 = {
    sha256 = "0zhqsas2mp2v71zlg77y0g4vi7y0qsbv952yr9ihm0ajsblvjwvc";
    url = "https://dl.espressif.com/dl/xtensa-esp32-elf-gcc8_2_0-esp-2020r2-linux-amd64.tar.gz";
  };
  xtensa-esp32s2-elf-gcc8_2_0-esp-2020r2-linux-amd64 = {
    sha256 = "0px6d165wrq85jv0rzmylv7bqksydd3y9pmwsqxvfwzpjs5d3vzm";
    url = "https://dl.espressif.com/dl/xtensa-esp32s2-elf-gcc8_2_0-esp-2020r2-linux-amd64.tar.gz";
  };
}
